# This is a basic workflow to help you get started with Actions

# name: CI

# Controls when the workflow will run
# on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
  # This workflow contains a single job called "build"
  # build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Use Node.js
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: "18.x"
    #   - name: node_modules installing
    #     run: npm install
    #   - name: lint:ts
    #     run: npm run lint:ts
    #   - name: lint:scss
    #     run: npm run lint:scss
    #   - name: build:prod
    #     run: npm run build:prod
    #   - name: test:unit
    #     run: npm run test:unit
    #   - name: storybook:build
    #     run: npm run storybook:build
    #   - name: test:ui:ci
    #     run: npm run test:ui:ci

name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# permissions:
#   contents: write
#   pages: write
#   id-token: write
# concurrency:
#   group: "pages"
#   cancel-in-progress: true
jobs:
  build-and-ui-testing:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()
      # - name: Generate HTML report
      #   run: npm run test:ui:report
      #   if: always()
      # - name: Setup Pages
      #   uses: actions/configure-pages@v2
      #   if: always()
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1
      #   if: always()
      #   with:
      #     path: '.loki'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   if: always()
      #   uses: actions/deploy-pages@v1

  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        if: always()
        run: npm run test:unit
