# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: node_modules installing
        run: npm install
      - name: build:prod
        run: npm run build:prod
      - name: test:unit
        run: npm run test:unit
      - name: storybook:build
        run: npm run storybook:build
      - name: test:ui:ci
        run: npm run test:ui:ci
      - name: lint:ts
        run: npm run lint:ts
      - name: lint:scss
        run: npm run lint:scss
